package net.spokenword.core.event;

public enum EventType {
    ENTITY_DEATH,
    OWNED_DEATH,
    PLAYER_JOIN,
    PLAYER_LEAVE,
    SELF_KICKED,
    SELF_LEAVE,
    SELF_JOIN,
    BLOCK_BREAK,
    BLOCK_PLACE,
    SELF_DEATH_PVE,
    SELF_DEATH_PVP,
    KILLED_PVE,
    KILLED_PVP,
    SELF_RESPAWN,
    PLAYER_CHAT,
    PLAYER_MESSAGE,
    SELF_LEVEL_UP,
    ITEM_PICKUP,
    ITEM_DROP,
    PLAYER_DEATH,
}
